### ISSUE TITLE
Join effort

### ISSUE THREAD

**Issue by sfrique** [laurentverbruggen/concourse-bitbucket-pullrequest-resource#19]
Hello,

I see a message saying that this repo will not be active maintained, and there is this repo: https://github.com/mmb/concourse-bitbucket-pullrequest-resource (fork)  that says it will maintain it.

Is it possible for you guys to coordinate and keep an unified repo? @mmb @laurentverbruggen 

I think both would benefit from it. The repos still really close.

Regards

**Comment by mmb** [comment]
I'm open to collaboration but I didn't want to bother @laurentverbruggen with my PRs if he no longer wants to maintain it.

I forked it because we are actively using the resource and need a place to make bug fixes and changes.

**Comment by laurentverbruggen** [comment]
I try to merge pull requests when I have the time and when it doesn't deviate that much from the original code. I don't have time to test it, so it must be clear that the change will not break anything.

As for collaboration, I can only ask @mmb to do the necessary merges (to his fork) or PRs (to my repo) to have all changes in one repo. Removing this repo is not really a solution since there will certainly be people using this repository.

**Comment by sfrique** [comment]
@laurentverbruggen if isn't too much to ask, can you add a note you your repo that further PRs and development will be done in @mmb repo? You already have a note that it won't be "actively maintained" 

That way most effort should be focus on only one repo.

Sorry to disturb both of you.

**Comment by laurentverbruggen** [comment]
Ok, I'll do that if all changes from this repository are added to the mmb repository. I've tried creating a pull request but apparently I can't do an upstream pull request so @mmb will have to pull the changes in. Let me know when you have done that and I'll add the comment.

**Comment by sfrique** [comment]
Thanks @laurentverbruggen lets hope @mmb is ok with that!

Really appreciate.

**Comment by mmb** [comment]
I'll do my best to pull in all changes from upstream.

**Comment by mmb** [comment]
All the commits in this repo have been pulled into mmb/concourse-bitbucket-pullrequest-resource.

Thanks for writing this resource @laurentverbruggen.

**Comment by laurentverbruggen** [comment]
I've included the message. Good luck with the resource!

**Comment by sfrique** [comment]
Thank you all.
Appreciate the effort and the resource!
