### ISSUE TITLE
How to handle PR spanning multiple repos

### ISSUE THREAD

**Issue by philicious** [laurentverbruggen/concourse-bitbucket-pullrequest-resource#4]
Hi,

how would I handle a PR that spans over multiple repos, i.e.

`cool-service` has a dependency on `some-shared-lib` and some new feature requires changes to both. now for building, both repos need to have the feature branch checked out

can I somehow do this with your resource ?

**Comment by laurentverbruggen** [comment]
A pull request is always targetting a single repository. If you want to
include a change in another repository you create a version/build of that
other repository and include that version in you cool-service change so it
will be included in the PR build.

Op wo 21 jun. 2017 om 17:47 schreef philicious <notifications@github.com>:

**Comment by philicious** [comment]
@laurentverbruggen yep. thats the general approach. fair enough.
I just had the vague hope there might be a way with concourse to checkout same branch on multiple repos. but anyways..

thx for this resource :) 👍
