### ISSUE TITLE
Not working with Bitbucket Cloud

### ISSUE THREAD

**Issue by philicious** [laurentverbruggen/concourse-bitbucket-pullrequest-resource#7]
Hi,

this resource isnt working for me with Bitbucket Cloud as you get the PRs with `git ls-remote` ( https://github.com/laurentverbruggen/concourse-bitbucket-pullrequest-resource/blob/master/assets/check#L56 ) but that isnt listing PRs. 

I guess you are using it with Bitbucket Server (self-hosted) and there its working ?

Best !

**Comment by fewknow** [comment]
@philicious did you ever get this to work?  I am trying now and it doesn't see any of my PR's

**Comment by philicious** [comment]
@fewknow kinda.  I used this resource now productively https://github.com/zarplata/concourse-git-bitbucket-pr-resource . I added support for Bitbucket Cloud and it also supports self-hosted Bitbucket Server

**Comment by laurentverbruggen** [comment]
Yes, this resource was developed for Bitbucket Server. Since this repository is no longer actively maintained I will close this since I won't be fixed.

**Comment by philicious** [comment]
@laurentverbruggen maybe you could add to README that its only supposed to work with self-hosted Bitbucket Server and not with Cloud so people dont get confused or waste time when actually working with Bitbucket Cloud and finding your resource

**Comment by laurentverbruggen** [comment]
yes, you are right. I'll add it.
